export const styles = {
  bg: { backgroundColor: "white", width: "100%" },
  logo: {
    mr: 1,
    fontFamily: "monospace",
    fontWeight: 700,
    color: "black",
    textDecoration: "none",
  },
  menu: { flexGrow: 1, display: { xs: "flex", md: "none" } },
  page: {
    display: { xs: "block", md: "none" },
  },
  page1: {
    display: { xs: "none", md: "block" },
  },
  mpage: { flexGrow: 1, display: { xs: "none", md: "flex" } },
  pageLink: {
    ml: 2,
    opacity: "0.8",
    textTransform: "capitalize",
    color: "black",
    display: "block",
    fontSize: "12px",
    fontFamily: "sans-serif",
    fontWeight: "bold",
  },
  flexGrow0: { flexGrow: 0 },
  mt45: { mt: "45px" },
  searchBox: {
    marginTop: 1,
    display: "flex",
    border: "1px solid rgba(0,0,0,0.25)",
    borderRadius: "5px",
    marginRight: 1,
    marginBottom: 1,
  },
  searchBox1: {
    marginTop: 1,
    width: "66%",
    display: "flex",
    border: "1px solid rgba(0,0,0,0.25)",
    borderRadius: "5px",
    marginRight: 1,
    marginBottom: 1,
    height: "auto",
    position: "relative",
  },
  searchAdd: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRight: "1px solid rgba(0,0,0,0.25)",
    marginRight: "-21px",
  },
  address: {
    border: "none",
    color: "black",
    paddingLeft: "5px",
    paddingRight: "5px",
    fontWeight: "bold",
    opacity: "0.8",
    height: "30px",
    boxShadow: "none",
    ".MuiOutlinedInput-notchedOutline": { border: 0 },
    "&.MuiOutlinedInput-root:hover .MuiOutlinedInput-notchedOutline": {
      border: 0,
    },
    "&.MuiOutlinedInput-root.Mui-focused .MuiOutlinedInput-notchedOutline": {
      border: 0,
    },
  },
  help: {
    border: "2px solid #228fad",
    color: "#228fad",
    borderRadius: "5px",
    padding: "7px",
    marginRight: 2,
    fontWeight: "bold",
    cursor: "pointer",
    transition: "all 0.3s ease-in-out",
    "&:hover": {
      backgroundColor: "rgba(34,143,173,0.75)",
      color: "white",
    },
  },
  icons: {
    marginRight: 1,
    cursor: "pointer",
  },
  iconColor: { color: "rgba(0,0,0,0.75)" },
  pad: {
    padding: "10px",
  },
  text1: {
    border: "2px solid #228fad",
    color: "#228fad",
    borderRadius: "5px",
    padding: "15px 10px",
    marginRight: 2,
    marginLeft: 2,
    fontWeight: "bold",
    backgroundColor: "#FFFFFF",
    marginBottom: 1,
    marginTop: 1,
    cursor: "pointer",
    transition: "all 0.3s ease-in-out",
    "&:hover": {
      backgroundColor: "rgba(34,143,173,0.75)",
      color: "white",
    },
  },
  font: {
    fontSize: "12px",
    fontWeight: "bold",
  },
  bx: {
    width: "159px",
    padding: "0px 7px",
    borderRadius: "5px",
    fontSize: "13px",
    fontFamily: "sans-serif",
    opacity: "0.8",
    backgroundColor: "#FFFFFF",
    boxShadow: "none",
    ".MuiOutlinedInput-notchedOutline": { border: 0 },
    "&.MuiOutlinedInput-root:hover .MuiOutlinedInput-notchedOutline": {
      border: 0,
    },
    "&.MuiOutlinedInput-root.Mui-focused .MuiOutlinedInput-notchedOutline": {
      border: 0,
    },
  },
  mr2: {
    marginRight: 2,
    marginBottom: 1,
    marginTop: 1,
  },
  featureBx: { display: "flex", flexWrap: "wrap" },
  bx1: {
    width: "100%",
    padding: "0px 7px",
    borderRadius: "5px",
    marginBottom: 1,
    border: "none",
    fontSize: "12px",
    fontFamily: "sans-serif",
    opacity: "0.8",
    fontWeight: "bold",
    backgroundColor: "#FFFFFF",
    boxShadow: "none",
    ".MuiOutlinedInput-notchedOutline": { border: 0 },
    "&.MuiOutlinedInput-root:hover .MuiOutlinedInput-notchedOutline": {
      border: 0,
    },
    "&.MuiOutlinedInput-root.Mui-focused .MuiOutlinedInput-notchedOutline": {
      border: 0,
    },
  },
  cat: {
    width: "99%",
    marginBottom: 1,
    marginTop: 1,
    backgroundColor: "#FFFFFF",
    border: "1px solid rgba(0,0,0,0.25)",
    borderRadius: "5px",
    padding: "3px",
  },
  mWidth: {
    width: "100%",
    marginTop: 1,
    display: "flex",
    border: "1px solid rgba(0,0,0,0.25)",
    borderRadius: "5px",
    marginBottom: 1,
    height: "50px",
    position: "relative",
  },
  bx2: {
    width: "100%",
    padding: "0px 7px",
    borderRadius: "5px",
    marginBottom: 1,
    border: "none",
    fontSize: "12px",
    fontFamily: "sans-serif",
    opacity: "0.8",
    fontWeight: "bold",
    boxShadow: "none",
    ".MuiOutlinedInput-notchedOutline": { border: 0 },
    "&.MuiOutlinedInput-root:hover .MuiOutlinedInput-notchedOutline": {
      border: 0,
    },
    "&.MuiOutlinedInput-root.Mui-focused .MuiOutlinedInput-notchedOutline": {
      border: 0,
    },
  },
  banner: {
    width: "100%",
  },
  bx3: {
    margin: "10px",
    boxShadow: "rgba(0, 0, 0, 0.24) 0px 3px 8px",
    backgroundColor: "#FFFFFF",
    borderRadius: "5px",
    padding: "25px",
  },
  bx4: {
    display: "flex",
    justifyContent: "center",
    gap: "35px",
    flexWrap: "wrap",
    width: "90%",
    margin: "auto",
  },
  itemsBx: {
    boxShadow:
      "rgba(60, 64, 67, 0.3) 0px 1px 2px 0px, rgba(60, 64, 67, 0.15) 0px 2px 6px 2px",
    padding: "10px",
    borderRadius: "5px",
    width: "170px",
    height: "auto",
    cursor: "pointer",
  },
  itemImg: {
    maxWidth: "100%",
    minWidth: "50%",
  },
  itemsImg: {
    maxWidth: "100%",
    minWidth: "50%",
    height: "130px",
  },
  ItemFont: {
    fontSize: "13px",
    textAlign: "center",
    fontWeight: "bold",
  },
  heading: {
    fontFamily: "sans-serif",
    fontWeight: "bold",
    fontSize: "17px",
  },
  headingBx: {
    margin: "20px auto",
    width: "85%",
    display: "flex",
    justifyContent: "space-between",
  },
  respHeading: {
    margin: "10px auto",
    width: "85%",
    display: "flex",
    justifyContent: "space-between",
  },
  respItemsBx: {
    boxShadow:
      "rgba(60, 64, 67, 0.3) 0px 1px 2px 0px, rgba(60, 64, 67, 0.15) 0px 2px 6px 2px",
    padding: "10px",
    borderRadius: "5px",
    width: "130px",
    height: "auto",
    cursor: "pointer",
  },
  respBx4: {
    display: "flex",
    justifyContent: "center",
    gap: "25px",
    flexWrap: "wrap",
  },
  respBx3: {
    margin: "10px",
    boxShadow: "rgba(0, 0, 0, 0.24) 0px 3px 8px",
    backgroundColor: "#FFFFFF",
    borderRadius: "5px",
    padding: "10px",
  },
  respItemFont: {
    fontSize: "10px",
    textAlign: "center",
    fontWeight: "bold",
  },
  avatar: { width: "35px", height: "35px" },
  mainImg:{display:'flex', justifyContent:'center', alignItems:'center'},
  nameDesc: {
    fontSize: "13px",
    fontWeight: "bold",
    fontFamily: "sans-serif",
    lineHeight: "15px",
    height:'30px',
    overflowY:'scroll'
  },
  desc: {
    fontSize: "13px",
    fontWeight: "bold",
    fontFamily: "sans-serif",
    lineHeight: "15px",
  },
  desc1: {
    fontSize: "13px",
    fontWeight: "bold",
    fontFamily: "sans-serif",
    lineHeight: "15px",
    padding: "5px 10px",
    cursor: "pointer",
  },
  desc2:{
    fontSize: "13px",
    fontWeight: "bold",
    fontFamily: "sans-serif",
    lineHeight: "15px",
    marginBottom:1,
  },
  respDesc: {
    fontSize: "11px",
    fontWeight: "bold",
    fontFamily: "sans-serif",
  },
  code: {
    fontSize: "12px",
    color: "grey",
    fontFamily: "sans-serif",
    fontWeight: "bold",
    // marginTop: 1,
    // marginBottom: 1,
  },
  code1: {
    fontSize: "13px",
    color: "grey",
    fontFamily: "sans-serif",
    fontWeight: "bold",
  },
  price: { color: "black", fontWeight: "bold", fontSize: "16px" },
  tx: {
    fontSize: "13px",
    color: "#228fad",
    fontFamily: "sans-serif",
    fontWeight: "bold",
  },
  respTx: {
    fontSize: "11px",
    color: "#228fad",
    fontFamily: "sans-serif",
    fontWeight: "bold",
  },
  btnBx: { display: "flex", marginTop: 1},
  btnIncDec: {
    display: "flex",
    border: "1px solid rgba(0,0,0,0.25)",
    marginRight: 1,
    padding: "5px",
    width: "40%",
    borderRadius: "5px",
    justifyContent: "space-evenly",
  },
  likeBtn: {
    border: "1px solid #228fad",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px 5px",
    borderRadius: "5px",
    width: "20%",
    cursor: "pointer",
  },
  addBtn: {
    marginTop: 1,
    marginBottom:1
  },
  addToBtn: {
    backgroundColor: "#228fad",
    color: "#FFFFFF",
    fontSize: "12px",
    fontFamily: "sans-serif",
    fontWeight: "bold",
    textTransform: "capitalize",
    width: "80%",
    padding: "10px 15px",
    "&:hover": {
      backgroundColor: "rgba(34,143,173,0.75)",
      color: "white",
    },
  },
  sAddToCart: {
    backgroundColor: "#228fad",
    color: "#FFFFFF",
    fontSize: "12px",
    fontFamily: "sans-serif",
    fontWeight: "bold",
    textTransform: "capitalize",
    padding: "10px 15px",
    "&:hover": {
      backgroundColor: "rgba(34,143,173,0.75)",
      color: "white",
    },
  },
  respAddToBtn: {
    backgroundColor: "#228fad",
    color: "#FFFFFF",
    fontSize: "12px",
    fontFamily: "sans-serif",
    fontWeight: "bold",
    textTransform: "capitalize",
    width: "100%",
    padding: "10px 15px",
    "&:hover": {
      backgroundColor: "rgba(34,143,173,0.75)",
      color: "white",
    },
  },
  respBtnBx: { display: "flex", justifyContent: "space-around" },
  respLikeBtn: {
    border: "2px solid #228fad",
    width: "20%",
    height: "fit-content",
    borderRadius: "5px",
    padding: "5px",
    marginTop: "10px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  block: {
    display: "block",
  },
  searchText: {
    border: "1px solid rgba(0,0,0,0.25)",
    backgroundColor: "rgba(151,191,202,0.25)",
    padding: "5px",
    borderRadius: "5px",
  },
  searchBx: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    width: "85%",
    margin: "auto",
  },
  cpyBx: { marginTop: 8, marginBottom: 1 },
  cpy: {
    textAlign: "center",
    fontSize: "13px",
    fontFamily: "sans-serif",
    opacity: "0.8",
  },
  slider: { width: "85%", margin: "auto" },
  tx1: {
    color: "#228fad",
    fontSize: "12px",
    fontWeight: "bold",
    fontFamily: "sans-serif",
    cursor: "pointer",
    "&:hover": {
      color: "blue",
    },
  },
  sliderBx: { marginTop: "10px", marginBottom: "10px" },
  inputBox: {
    position: "absolute",
    marginTop: "50px",
    border: "1px solid rgba(0,0,0,0.25)",
    backgroundColor: "#FFFFFF",
    width: "100%",
    borderBottomRightRadius: "5px",
    borderBottomLeftRadius: "5px",
    zIndex: 1000,
    height: "60vh",
    overflowY: "scroll",
  },
  textInput: {
    padding: "5px 10px",
    width: "auto",
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "rgba(0,0,0,0.15)",
    },
  },
  s1: { display: "flex", flexWrap: "wrap", padding:'10px', paddingBottom:'10px', width:'90%', margin:'auto', gap:'20px'},
  s11: { display: "flex", flexWrap: "wrap", padding:'10px', paddingBottom:'10px'},
  s2: { display: "flex", justifyContent: "center", marginBottom:4},
  s3: {
    margin: "15px",
    borderRadius: "5px",
    backgroundColor: "rgba(151,191,202,0.25)",
    width: "80px",
    height: "80px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  sImg: { width: "70px", height: "70px" },
  lImg:{width:'200px', height:'200px'},
  s4: {
    borderRadius: "5px",
    backgroundColor: "rgba(151,191,202,0.25)",
    width: "300px",
    height: "300px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginLeft:2,
  },
  sBx:{display:"flex",marginTop:2},
  respSBx:{display:"flex",width:'70%',marginTop:2},
  dx:{width: '100%', marginLeft:2, marginRight:2},
  title:{ fontFamily: 'sans-serif', fontSize: '18px', fontWeight: 'bold', marginBottom:1},
  title1:{ fontFamily: 'sans-serif', fontSize: '13px', fontWeight: 'bold', marginBottom:1},
};
